"use client";

import { useState } from "react";
import Image from "next/image";
import { motion, AnimatePresence } from "framer-motion";
import { CheckCircle2, ChevronRight } from "lucide-react";

type Service = {
  title: string;
  desc: string;
  image: string;
};

const services: Service[] = [
  {
    title: "Zero-Capital Solar Lease",
    desc: "Switch to clean solar power with zero upfront CAPEX. We finance, construct, and operate roof or carport solar PV installations with immediate utility billing discounts.",
    image: "https://images.unsplash.com/photo-1613665813446-82a78c468a1d?q=80&w=600&auto=format&fit=crop"
  },
  {
    title: "DEWA Net Metering Integration",
    desc: "Seamless grid-tie engineering. Surplus clean energy generated by your facility is exported back to the DEWA grid, building net-energy billing credits in real-time.",
    image: "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?q=80&w=600&auto=format&fit=crop"
  },
  {
    title: "High-Precision MEP Execution",
    desc: "Integrated electromechanical and plumbing systems designed for luxury residential estates, high-rise office towers, and high-load industrial hubs.",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=600&auto=format&fit=crop"
  },
  {
    title: "Etihad ESCO Compliance",
    desc: "Safeguard regulatory compliance under Dubai's building rules. We provide comprehensive energy performance auditing and carbon offset calculations.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=600&auto=format&fit=crop"
  },
  {
    title: "24/7 Preventative AMC Support",
    desc: "Protect the lifetime value of your engineering assets. High-fidelity thermal drone auditing, inverter diagnostics, and quick-dispatch MEP emergency teams.",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=600&auto=format&fit=crop"
  }
];

export default function HighlighterServices() {
  const [activeIndex, setActiveIndex] = useState(0);

  return (
    <section className="py-20 lg:py-28 bg-[#FCFCFC]">
      <div className="wrapper max-w-7xl mx-auto px-6 grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
        
        {/* Left Column - Vertical Accordion List */}
        <div className="lg:col-span-6 space-y-6">
          <div>
            <span className="text-ras-gold text-xs font-bold uppercase tracking-widest mb-3 block">
              Tailored to Your Operations
            </span>
            <h2 className="text-4xl sm:text-5xl lg:text-6xl font-light text-ras-charcoal tracking-tightest leading-tight mb-8">
              B2B Engineering Value Propositions
            </h2>
          </div>

          <div className="flex flex-col space-y-3">
            {services.map((service, idx) => {
              const isActive = idx === activeIndex;
              return (
                <div
                  key={idx}
                  onMouseEnter={() => setActiveIndex(idx)}
                  className={`group p-6 rounded-2xl border transition-all duration-300 cursor-pointer flex items-start space-x-4 ${
                    isActive
                      ? "bg-ras-sand/40 border-ras-gold/30 shadow-md"
                      : "bg-transparent border-ras-grey/10 hover:border-ras-gold/30"
                  }`}
                >
                  <div className={`p-2 rounded-xl border transition-colors ${
                    isActive ? "bg-ras-gold text-white border-ras-gold" : "bg-white text-ras-grey border-ras-grey/15 group-hover:text-ras-gold"
                  }`}>
                    <CheckCircle2 className="h-5 w-5" />
                  </div>

                  <div className="flex-grow space-y-1">
                    <h3 className="text-lg font-semibold text-ras-charcoal flex items-center justify-between">
                      <span>{service.title}</span>
                      <ChevronRight className={`h-4 w-4 text-ras-gold transition-transform duration-300 ${
                        isActive ? "translate-x-1 opacity-100" : "opacity-0 group-hover:opacity-100 group-hover:translate-x-0.5"
                      }`} />
                    </h3>
                    <AnimatePresence initial={false}>
                      {isActive && (
                        <motion.p
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: "auto", opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{ duration: 0.3 }}
                          className="text-sm text-ras-grey leading-relaxed pt-2 overflow-hidden"
                        >
                          {service.desc}
                        </motion.p>
                      )}
                    </AnimatePresence>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Right Column - Smooth Image Transition Panel */}
        <div className="lg:col-span-6 relative aspect-[1.25] rounded-[28px] overflow-hidden shadow-2xl border border-ras-grey/15">
          <div className="absolute inset-0 bg-gradient-to-t from-ras-charcoal/40 via-transparent to-transparent z-10 pointer-events-none" />
          
          <AnimatePresence mode="wait">
            <motion.div
              key={activeIndex}
              initial={{ opacity: 0, scale: 1.02 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.98 }}
              transition={{ duration: 0.55, cubicBezier: [0.16, 1, 0.3, 1] }}
              className="absolute inset-0 w-full h-full"
            >
              <Image
                src={services[activeIndex].image}
                alt={services[activeIndex].title}
                fill
                sizes="(max-width: 768px) 100vw, 600px"
                className="object-cover"
                priority
              />
            </motion.div>
          </AnimatePresence>
        </div>

      </div>
    </section>
  );
}
